name: vapoursynth

on: [push, pull_request]

jobs:
  clippy-rustfmt:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy, rustfmt
    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Run clippy on all tests
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all --all-targets --all-features --exclude sample-plugin
    - name: Run clippy on the sample-plugin
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --package sample-plugin
        name: sample-plugin

  linux-tests:
    strategy:
      fail-fast: false

      matrix:
        toolchain:
         - stable-x86_64-unknown-linux-gnu
         - stable-i686-unknown-linux-gnu

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install VapourSynth on Ubuntu 64-bit
      if: matrix.toolchain == 'stable-x86_64-unknown-linux-gnu'
      run: build/script.sh

    - name: Install VapourSynth on Ubuntu 32-bit
      if: matrix.toolchain == 'stable-i686-unknown-linux-gnu'
      run: build/script.sh i686

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Run tests
      run: |
        cd vapoursynth
        python3 ../build/run-tests.py
    - name: Run sample-plugin tests
      run: |
        cd sample-plugin
        cargo build
        cargo run --bin test --features "cfg-if \
                  vapoursynth/vapoursynth-functions \
                  vapoursynth/vsscript-functions"
    - name: Run doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --all-features
    - name: Copy index into the target directory
      if: matrix.toolchain == 'stable-x86_64-unknown-linux-gnu'
      run: |
        cp build/index.html target/doc
    - name: Deploy documentation
      if: >
        matrix.toolchain == 'stable-x86_64-unknown-linux-gnu' &&
        github.event_name == 'push' &&
        github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc

  windows-tests:
    strategy:
      fail-fast: false

      matrix:
        toolchain:
         - stable-x86_64-pc-windows-msvc
         - stable-x86_64-pc-windows-gnu

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Install VapourSynth for Windows 64-bit
      run: |
        build/windows-script.ps1
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Run tests
      run: |
        $Env:Path += ";C:\Program Files\VapourSynth;"
        cd vapoursynth
        python ../build/run-tests.py
    - name: Build sample-plugin
      run: |
        $Env:Path += ";C:\Program Files\VapourSynth;"
        cd sample-plugin
        cargo build
    - name: Run sample-plugin tests
      run: |
        $Env:Path += ";C:\Program Files\VapourSynth;"
        cd sample-plugin
        cargo run --bin test --features "cfg-if `
                  vapoursynth/vapoursynth-functions `
                  vapoursynth/vsscript-functions"
    - name: Run doc
      run: cargo doc --all-features
